site_name: Campus Connect Docs
site_url: https://tylergeiger513.github.io/CampusConnect-Prod/

theme:
  name: material
  features:
    - content.code.copy
  icon: 
    admonition: 
      info: simple/helm
      abstract: simple/skaffold
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode


# make the landing page the index page
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Deployment:  
      - CI/CD: ci_cd.md
      - Local Deployment: local-deployment.md
  - Backend: 
      - Databases:
         - MongoDB: mongo.md
         - Redis: redis.md
      - Authentication: auth.md
      - Friends: friends.md
      - Channels: channels.md



markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      css_class: highlight
      guess_lang: false
  - pymdownx.tasklist:
      custom_checkbox: true
