apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicies.allowBackendEgressToDatabases.name }}
  namespace: {{ .Values.global.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.backend.appName }}
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - {{ .Values.database.redis.appName }}
                  - {{ .Values.database.mongo.appName }}
      ports:
        - protocol: TCP
          port: {{ .Values.database.redis.port }}
        - protocol: TCP
          port: {{ .Values.database.mongo.port }}
