apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-to-databases
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - redis
          - mongo
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: campus-connect-backend
