apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-egress-to-databases
spec:
  podSelector:
    matchLabels:
      app: campus-connect-backend
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - redis
                  - mongo
      ports:
        - protocol: TCP
          port: 6379  
        - protocol: TCP
          port: 27017  
