apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicies.allowIngressToBackend.name }}
  namespace: {{ .Values.global.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.backend.appName }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
         