apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicies.allowBackendToDatabases.name }}
  namespace: {{ .Values.global.namespace | default "default" }}
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - {{ .Values.database.redis.appName }}
          - {{ .Values.database.mongo.appName }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.backend.appName }}
