apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.appName }}
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    app: {{ .Values.backend.appName }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.appName }}
      annotations:
        keel.sh/policy: force
        keel.sh/trigger: poll
        keel.sh/pollSchedule: "@every 1m"
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image }}:{{ .Values.tagPolicy }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.port }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.name }}
        - secretRef:
            name: {{ .Values.configMap.name }}-secrets 
