apiVersion: apps/v1
kind: Deployment
metadata:
  name: campus-connect-backend
  labels:
    app: campus-connect-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campus-connect-backend
  template:
    metadata:
      labels:
        app: campus-connect-backend
      annotations:
        keel.sh/policy: force
        keel.sh/trigger: poll      
        keel.sh/pollSchedule: "@every 1m"
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image }}:{{ .Values.tagPolicy }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: campus-connect-config
