apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.global.namespace | default "default" }}
data:
  HOST: "0.0.0.0"
  DOMAIN: "{{ .Values.domain }}"
  BACKEND_PORT: "{{ .Values.backend.service.port }}"
  MONGO_HOST: "{{ .Values.database.mongo.appName }}"
  MONGO_PORT: "{{ .Values.database.mongo.port }}"
  MONGO_DB: "campusconnect_db"
  REDIS_HOST: "{{ .Values.database.redis.appName }}"
  REDIS_PORT: "{{ .Values.database.redis.port }}"
  LOG_LEVEL: "info" 
  NGINX_BACKEND_UPSTREAM: "{{ .Values.backend.service.name }}:{{ .Values.backend.service.port }}"
  NGINX_FRONTEND_UPSTREAM: "{{ .Values.frontend.service.name }}:{{ .Values.frontend.service.port }}"

  NODE_ENV: "production"
  API_PREFIX: "api"
  PORT: "{{ .Values.backend.service.port }}" 
  SESSION_LIFETIME: "86400000"
  COOKIE_SECURE: "false" 
  COOKIE_SAME_SITE: "strict"
  CORS_ORIGIN: "{{ .Values.domain }}"
  NGINX_NODE_PORT: "{{ .Values.frontend.service.port }}" 
