apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: campus-connect-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: "nginx"
  rules:
    - host: "{{ .Values.domain }}"  
      http:
        paths:
          # Frontend static files
          - path: /
            pathType: Prefix
            backend:
              service:
                name: campus-connect-frontend-service
                port:
                  number: 80

          # Backend API
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: campus-connect-backend-service
                port:
                  number: 3000

          # WebSockets (notifications)
          - path: /notifications/
            pathType: Prefix
            backend:
              service:
                name: campus-connect-backend-service
                port:
                  number: 3000

          # WebSockets (channels)
          - path: /channels/
            pathType: Prefix
            backend:
              service:
                name: campus-connect-backend-service
                port:
                  number: 3000

          # WebSockets (posts)
          - path: /posts/
            pathType: Prefix
            backend:
              service:
                name: campus-connect-backend-service
                port:
                  number: 3000
