apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.mongo.pvcName }}
  namespace: {{ .Values.global.namespace | default "default" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.mongo.storageSize }}
