apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.mongo.appName }}
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    app: {{ .Values.database.mongo.appName }}
spec:
  replicas: {{ .Values.database.mongo.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.database.mongo.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.mongo.appName }}
    spec:
      containers:
      - name: {{ .Values.database.mongo.appName }}
        image: {{ .Values.database.mongo.image }}
        ports:
        - containerPort: {{ .Values.database.mongo.port }}
        volumeMounts:
        - name: {{ .Values.database.mongo.volumeName }}
          mountPath: {{ .Values.database.mongo.mountPath }}
      volumes:
      - name: {{ .Values.database.mongo.volumeName }}
        persistentVolumeClaim:
          claimName: {{ .Values.database.mongo.pvcName }}
