apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.mongo.appName }}
  namespace: {{ .Values.global.namespace | default "default" }}
spec:
  selector:
    app: {{ .Values.database.mongo.appName }}
  ports:
    - port: {{ .Values.database.mongo.port }}
      targetPort: {{ .Values.database.mongo.port }}
  type: ClusterIP
