apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.redis.appName }}
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    app: {{ .Values.database.redis.appName }}
spec:
  replicas: {{ .Values.database.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.database.redis.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.redis.appName }}
    spec:
      containers:
      - name: {{ .Values.database.redis.appName }}
        image: {{ .Values.database.redis.image }}
        ports:
        - containerPort: {{ .Values.database.redis.port }}
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.configMap.name }}-secrets 
              key: REDIS_PASSWORD
