apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configMap.name }}-secrets 
  namespace: {{ .Values.global.namespace | default "default" }}
type: Opaque
data:
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | b64enc | quote }}
