name: ci

on:
  push:
    branches:
      - docs
permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Optional caching if you have large dependencies or a big site
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install MkDocs Material
        run: | 
          pip install mkdocs-material
          pip install mkdocs-video

      - name: Build site
        run: mkdocs build --verbose

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
